### ISSUE TITLE
Invalid apoc export graphml format

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#78] opened 2022-09-01 09:45 UTC
<a href="https://github.com/edacker"><img src="https://avatars.githubusercontent.com/u/57496775?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edacker](https://github.com/edacker)**
_Monday Nov 02, 2020 at 13:19 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1704_

----

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
valid graphML exported
![image](https://user-images.githubusercontent.com/57496775/97872423-02cc5980-1ce4-11eb-9e3f-983874c939cb.png)

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by neo-technology-build-agent** [comment] 2022-09-01 09:45
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vga91](https://github.com/vga91)**
_Tuesday Mar 02, 2021 at 11:29 GMT_

----

@edacker 
I was unable to replicate the bug.
Please, could you provide the dataset used, and the exported `.graphml` file? (it seems like the bug is at the beginning of the file)

**Comment by neo-technology-build-agent** [comment] 2022-09-01 09:45
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Thursday Apr 22, 2021 at 11:26 GMT_

----

@edacker ping

**Comment by neo-technology-build-agent** [comment] 2022-09-01 09:45
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Thursday May 13, 2021 at 16:19 GMT_

----

@edacker ping

**Comment by gem-neo4j** [comment] 2023-04-06 11:46
Closing as unable to reproduce

**Closed by gem-neo4j** 2023-04-06 11:46 UTC
