### ISSUE TITLE
apoc.meta.graph does not display ALL relationships

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#130] opened 2022-09-01 12:37 UTC
<a href="https://github.com/adriens"><img src="https://avatars.githubusercontent.com/u/5235127?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adriens](https://github.com/adriens)**
_Tuesday Aug 14, 2018 at 10:51 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/884_

----

# Runtime Configuration :

- Neo4J : 3.4.5 Enterprise
- APOC Installed 3.4.0.2

![2018-08-14 21_49_50-neo4j desktop - 1 1 8](https://user-images.githubusercontent.com/5235127/44087570-037f7760-a00c-11e8-8e6e-bf68b537dcc7.png)

![2018-08-14 21_50_29-neo4j desktop - 1 1 8](https://user-images.githubusercontent.com/5235127/44087609-1a0622c2-a00c-11e8-9155-dfa2a4f6531e.png)

# Description

i have a graph datbase with the following nodes and relationships (please note the relation between a column and a view):

![2018-08-14 21_42_53-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087338-440c1f78-a00b-11e8-9bac-1197e8906a7e.png)

but when i ask to apoc to show me the graph structure, i'm missing the relations between column->view

![2018-08-14 21_41_47-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087379-671d0f68-a00b-11e8-972e-f84068aa01e4.png)

I wonder how is this possible ?...in the documentation it is said that this procedure does not sample datas, but it looks like all nodes have not been parsed.

**Comment by neo-technology-build-agent** [comment] 2022-09-01 12:37
<a href="https://github.com/adriens"><img src="https://avatars.githubusercontent.com/u/5235127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adriens](https://github.com/adriens)**
_Tuesday Aug 14, 2018 at 10:54 GMT_

----

But db.schema seems to do the job :

![2018-08-14 21_53_00-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087768-9f5d963a-a00c-11e8-91fe-c9becd21309b.png)

**Comment by neo-technology-build-agent** [comment] 2022-09-01 12:37
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jexp](https://github.com/jexp)**
_Tuesday Aug 14, 2018 at 11:10 GMT_

----

Thanks for reporting. The problem is that the db-statistics only store half of the relationship information (only one label) so db.schema reports often false positives.

apoc.meta.graph samples a subset of the graph to confirm those relationships. In your case it seems that those `(:Column)-[:COLUMN_OF]->()` that were sampled didn't include `(:View)` and the views also didn't include those columns.

I'll check if there is an omission in the implementation.

**Comment by neo-technology-build-agent** [comment] 2022-09-01 12:37
<a href="https://github.com/adriens"><img src="https://avatars.githubusercontent.com/u/5235127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adriens](https://github.com/adriens)**
_Tuesday Aug 14, 2018 at 11:22 GMT_

----

Yes, it looks somehting like that...as to feed the graph, i first load column->tables then column-> views...

i do this in a sequential way. So the sample does maybe stop after a certain range, after the first load.

**Comment by neo-technology-build-agent** [comment] 2022-09-01 12:37
<a href="https://github.com/adriens"><img src="https://avatars.githubusercontent.com/u/5235127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adriens](https://github.com/adriens)**
_Tuesday Aug 14, 2018 at 11:22 GMT_

----

...hence causin the second sample to be skipped...

**Comment by neo-technology-build-agent** [comment] 2022-09-01 12:37
<a href="https://github.com/adriens"><img src="https://avatars.githubusercontent.com/u/5235127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adriens](https://github.com/adriens)**
_Wednesday Aug 15, 2018 at 00:18 GMT_

----

I've added new kind of nodes and it seems like having added this has changed the sample used , now 

`db.schema` and `call apoc.meta.graph()` give the same output, see below the correct relationships getting out of `Column` :

![2018-08-15 11_15_27-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44125174-ccd35878-a07c-11e8-965b-6b173217b3ee.png)

![2018-08-15 11_15_06-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44125183-d5c8c044-a07c-11e8-90b8-3cdd47681992.png)

**Comment by gem-neo4j** [comment] 2023-04-06 11:39
We have recently released (4.4.0.14 and 5.5.0) fixes for these procedures that apply fixes to the sampling. I cannot reproduce this issue, so will close this issue as assumed fixed. If you come across it in those or future builds feel free to reopen and supply a reproducible case :) Thank you!

**Closed by gem-neo4j** 2023-04-06 11:39 UTC
